version: '3'

services:
  app:
    build: .
    container_name: transactions-backend
    volumes: 
      - .:/go/src/
    networks:
      - kafka_network
      - api_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  kafka_network:
    external:
      name: apache-kafka_default
  api_network:
    external:
      name: mongodb_mongo_network