version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - api_network
      - kafka_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  api_network:
    external:
      name: mongodb_mongo_network 
  kafka_network:
    external:
      name: apache-kafka_default